### PR TITLE
Merge pull request #3 from CrystallineButterfly/master

### PR DESCRIPTION
**Pull request by CrystallineButterfly**
Hi; Here is a pull request to ask anyone, if changes need to be made? 

Thank you- K

### CODE REVIEW

**Review by zainsadaqat — CHANGES_REQUESTED** [review]
# Hello @CrystallineButterfly  😃 😃 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have linters attached. Also please don't merge the Pull Request until it gets approved by the Code Reviewer. 😄 
If you still feel confused, you may contact me via slack.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏



Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by CrystallineButterfly** [comment]
Hi @zainsadaqat 

Thank you for the constructive feedback, I am not sure how to add linters to my github, Please could you point me in the right direction? 

I love this, happy coding also man! 💯

**Comment by zainsadaqat** [comment]
Hi, @CrystallineButterfly!

Please follow this guide [Linters](https://github.com/microverseinc/linters-config/tree/master/html-css) step by step. If you face any difficulty, feel free to contact me via Slack.

**Comment by CrystallineButterfly** [comment]
Hi @zainsadaqat I feel I have made progress and completed adding linters, please confirm if this is right or wrong for me; 


https://github.com/CrystallineButterfly/Hello-Microverse-Code-review-challenge/pull/7

Here is the link to the code review!

**Pull request merged**
